### ISSUE TITLE
Rust code fails with `wasm-bindgen` version `0.2.80`

### ISSUE THREAD

**Issue by mikonieminen** [warp-contracts/warp-wasm-templates#11]
When upgrading `wasm-bindgen` to version `0.2.80` tests start to fail:
```
  ● Testing the Profit Sharing Token › should properly deploy contract

    TypeError: Cannot read properties of null (reading '1')

      77 |
      78 |     // deploying contract using the new SDK.
    > 79 |     contractTxId = await smartweave.createContract.deploy(
         |                    ^
      80 |       {
      81 |         wallet,
      82 |         initState: JSON.stringify(initialState),

      at matchMutClosureDtor (node_modules/redstone-smartweave/src/core/modules/impl/wasm/wasm-bindgen-tools.ts:4:15)
      at DefaultCreateContract.deploy (node_modules/redstone-smartweave/src/core/modules/impl/DefaultCreateContract.ts:83:41)
      at tests/contract.spec.ts:79:20
```

**Comment by ppedziwiatr** [comment]
Fixed in https://github.com/warp-contracts/warp/pull/219
